# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GH_REGISTRY: "ghcr.io"

jobs:
  # https://docs.docker.com/build/ci/github-actions/push-multi-registries/
  build_publish_app_frontend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          IMAGE_NAME: "rancher/supportability-review-app-frontend"
        with:
          context: ./package
          file: ./package/Dockerfile.app-frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
