# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SONOBUOY_COMMIT_HASH: "9c04b0b"
  SONOBUOY_MIRROR_TAG: "v0.57.1-rancher2"
  SONOBUOY_GH_REGISTRY: "ghcr.io"
  SONOBUOY_IMAGE_NAME: "masap/mirrored-sonobuoy-sonobuoy"
# SONOBUOY_IMAGE_NAME: "rancher/mirrored-sonobuoy-sonobuoy"

jobs:
  pull_push_sonobuoy_image_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push sonobuoy images
        run: |
          for arch in amd64 arm64 ppc64le s390x; do
            docker pull sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }}
            docker tag sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }} ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:${arch}-${{ env.SONOBUOY_MIRROR_TAG }}
            docker push ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:${arch}-${{ env.SONOBUOY_MIRROR_TAG }}
          done
          docker image ls

  publish_sonobuoy_image_manifest:
    needs: [pull_push_sonobuoy_image_linux]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Manifest create
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:${{ env.SONOBUOY_MIRROR_TAG }}
          sources: |
            ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:amd64-${{ env.SONOBUOY_MIRROR_TAG }}
            ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:arm64-${{ env.SONOBUOY_MIRROR_TAG }}
            ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:ppc64le-${{ env.SONOBUOY_MIRROR_TAG }}
            ${{ env.SONOBUOY_GH_REGISTRY }}/${{ env.SONOBUOY_IMAGE_NAME }}:s390x-${{ env.SONOBUOY_MIRROR_TAG }}
