# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_sonobuoy_image_manifest:
    runs-on: ubuntu-latest
    env:
      SONOBUOY_COMMIT_HASH: 9c04b0b
      GH_REGISTRY: "docker.io"
      IMAGE_NAME: "masap20220915/mirrored-sonobuoy-sonobuoy"
    steps:
      - name: Pull sonobuoy images
        run: |
          for arch in amd64 arm64 ppc64le s390x; do
            docker pull sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }}
            docker tag sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }} ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
          done
          docker image ls
