# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GH_REGISTRY: "ghcr.io"

jobs:
  # https://docs.docker.com/build/ci/github-actions/push-multi-registries/
  build_publish_app_frontend_image:
    strategy:
      matrix:
        image: [supportability-review, supportability-review-internal]
        make-target: [push-image, push-image-internal]
        tag: [v0.126.0-20251020, latest]
        platforms: ["linux/amd64,linux/arm64", "linux/arm64", "linux/amd64"]
        exclude:
          - image: supportability-review
            make-target: push-image-internal
          - image: supportability-review-internal
            make-target: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Set tag with platform suffix
        id: set-tag
        run: |
          if [ "${{ matrix.platforms }}" == "linux/arm64" ]; then
            echo "final_tag=${{ matrix.tag }}-arm64" >> $GITHUB_ENV
          elif [ "${{ matrix.platforms }}" == "linux/amd64" ]; then
            echo "final_tag=${{ matrix.tag }}-amd64" >> $GITHUB_ENV
          else
            echo "final_tag=${{ matrix.tag }}" >> $GITHUB_ENV
          fi
      - name: Show labels
        run: |
          echo '${{ matrix.image }}'
          echo '${{ matrix.make-target }}'
          echo '${{ env.final_tag }}'
          echo '${{ matrix.platforms }}'

  build_publish_app_frontend_image_include:
    strategy:
      # For sequential execution, to leverage both docker buildx
      # caching and to avoid each job having to push the same layers
      # to the target registry.
      max-parallel: 1
      matrix:
        include:
          # Three images are created:
          # - Multi-arch manifest for both amd64 and arm64
          - tag-suffix: ""
            platforms: linux/amd64,linux/arm64
          # - arm64 manifest
          - tag-suffix: "-arm64"
            platforms: linux/arm64
          # - amd64 manifest
          - tag-suffix: "-amd64"
            platforms: linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Show labels
        run: |
          echo '${{ matrix.tag-suffix }}'
          echo '${{ matrix.platforms }}'
