# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_sonobuoy_image_manifest:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      SONOBUOY_COMMIT_HASH: 9c04b0b
      GH_REGISTRY: "ghcr.io"
      IMAGE_NAME: "masap/mirrored-sonobuoy-sonobuoy"
#     IMAGE_NAME: "rancher/mirrored-sonobuoy-sonobuoy"
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push sonobuoy images
        run: |
          for arch in amd64 arm64 ppc64le s390x; do
            docker pull sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }}
            docker tag sonobuoy/sonobuoy:${arch}-${{ env.SONOBUOY_COMMIT_HASH }} ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
            docker push ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
          done

      - name: Manifest create
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:v0.57.1-rancher2
          sources: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-v0.57.1-rancher2
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-v0.57.1-rancher2
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:ppc64le-v0.57.1-rancher2
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:s390x-v0.57.1-rancher2

#          docker manifest rm ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
#          docker manifest create masap20220915/sonobuoy:v0.57.1-rancher1 masap20220915/sonobuoy:amd64-v0.57.1-rancher1 masap20220915/sonobuoy:arm64-v0.57.1-rancher1
#          docker manifest inspect ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
#          docker manifest push ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${arch}-v0.57.1-rancher2
#          docker image ls
